// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EditFollowUpController from "./edit_follow_up_controller.js"
application.register("edit-follow-up", EditFollowUpController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import MapController from "./map_controller.js"
application.register("map", MapController)

import SearchButtonController from "./search_button_controller.js"
application.register("search-button", SearchButtonController)

import SearchUsersController from "./search_users_controller.js"
application.register("search-users", SearchUsersController)

import SwiperController from "./swiper_controller.js"
application.register("swiper", SwiperController)
