// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import HomeCardsController from "./home_cards_controller.js"
application.register("home-cards", HomeCardsController)

import MapController from "./map_controller.js"
application.register("map", MapController)

import SearchButtonController from "./search_button_controller.js"
application.register("search-button", SearchButtonController)

import SwiperController from "./swiper_controller.js"
application.register("swiper", SwiperController)
