meta_product_name: "Tutti Frutti"
meta_title: "Tutti Frutti - Mangez de saison"
meta_description: "Découvrez le pouvoir des fruits et légumes de saison"
meta_image: "meta-og.jpg" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
